apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ssh-proxy
spec:
  version: "v0.1.1"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/infinite-turtles/kubectl-ssh-proxy/releases/download/v0.3.0/kubectl-ssh-proxy_linux_amd64.tar.gz
    sha256: "c36c945e07675b39a7b7215cd394a64e1095a4745f909ee1cb2593513d55a0cd"
    files:
    - from: "./kubectl-ssh-proxy"
      to: "."
    bin: "kubectl-ssh-proxy"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/infinite-turtles/kubectl-ssh-proxy/releases/download/v0.3.0/kubectl-ssh-proxy_darwin_amd64.tar.gz
    sha256: "68cdfe07837c058af84b4df7b44e4783055c521f27d7da80bce7dcbb857ed2d2"
    files:
    - from: "./kubectl-ssh-proxy"
      to: "."
    bin: "kubectl-ssh-proxy"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/infinite-turtles/kubectl-ssh-proxy/releases/download/v0.3.0/kubectl-ssh-proxy_windows_amd64.zip
    sha256: "d088dda5f39a806e39c604d22092432f53b7eee722cca0c87b730b57895f6efb"
    files:
    - from: "/kubectl-ssh-proxy.exe"
      to: "."
    bin: "kubectl-ssh-proxy.exe"
  shortDescription: Proxy OpenSSH client tools through Kubernetes pod
  homepage: https://github.com/infinite-turtles/kubectl-ssh-proxy
  caveats: |
    Usage:
      $ kubectl ssh-proxy

    Example:
      $ kubectl ssh-proxy ssh user@host

    For additional options:
      $ kubectl ssh-proxy --help

  description: |
    Proxy OpenSSH client tools through Kubernetes pod
