apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ssh-proxy
spec:
  version: "v0.1.1"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/infinite-turtles/kubectl-ssh-proxy/releases/download/v0.2.0/kubectl-ssh-proxy_linux_amd64.tar.gz
    sha256: "e1ab9a583d1b7e9cdf8af30eec4f1452aae83e62dfe9aaf27080aff13ee9113c"
    files:
    - from: "./kubectl-ssh-proxy"
      to: "."
    bin: "kubectl-ssh-proxy"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/infinite-turtles/kubectl-ssh-proxy/releases/download/v0.2.0/kubectl-ssh-proxy_darwin_amd64.tar.gz
    sha256: "5909072a6579f2bcc47fc302597d7978f57876699fc320d61c9551d93a261709"
    files:
    - from: "./kubectl-ssh-proxy"
      to: "."
    bin: "kubectl-ssh-proxy"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/infinite-turtles/kubectl-ssh-proxy/releases/download/v0.2.0/kubectl-ssh-proxy_windows_amd64.zip
    sha256: "633faab92f25799c04ae53f66878d8dac26e2074d3ce5efe28f180808cd162b4"
    files:
    - from: "/kubectl-ssh-proxy.exe"
      to: "."
    bin: "kubectl-ssh-proxy.exe"
  shortDescription: Proxy OpenSSH client tools through Kubernetes pod
  homepage: https://github.com/infinite-turtles/kubectl-ssh-proxy
  caveats: |
    Usage:
      $ kubectl ssh-proxy

    Example:
      $ kubectl ssh-proxy ssh user@host

    For additional options:
      $ kubectl ssh-proxy --help

  description: |
    Proxy OpenSSH client tools through Kubernetes pod
